version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-eks: circleci/aws-eks@1.1.0
  slack: circleci/slack@4.4.2

jobs:
  notify-on-start:
    parallelism: 1
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: 'deployments'
          template: basic_success_1
          event: pass

  notify-on-success:
    parallelism: 1
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: 'deployments'
          template: success_tagged_deploy_1
          event: pass

workflows:
  build-deploy-to-k8s:
    jobs:
      - notify-on-start:
          filters:
              branches:
                only:
                  - deploy
                  - master
          context: 
            - slack-secrets

      - aws-ecr/build-and-push-image:
          requires:
            - notify-on-start      
          filters:
              branches:
                only:
                  - deploy
                  - master
          context:
            - hexa-<< pipeline.git.branch >>
          repo: beee-workmgt
          dockerfile: docker/app/Dockerfile
          tag: $CIRCLE_SHA1  

      - aws-eks/update-container-image:
          name: deploy-to-staging
          requires:
            - aws-ecr/build-and-push-image
          filters:
              branches:
                only:
                  - deploy
          context:
            - hexa-deploy
          cluster-name: $EKS_CLUSTER_NAME
          aws-region: $AWS_REGION
          resource-name: "deployment/workmgt"
          container-image-updates: "beee-workmgt=$AWS_ECR_ACCOUNT_URL/beee-workmgt:$CIRCLE_SHA1"
          get-rollout-status: true
          watch-rollout-status: true
          namespace: default
          record: true
          
      - notify-on-success:
          name: notify-on-success-staging
          requires:
            - deploy-to-staging
          context: 
            - slack-secrets
      
      - slack/on-hold:
          context: slack-secrets
          channel: 'deployments'
          mentions: '<@U0PKAAQBB>, <@U0ADZSDP1>'
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires: 
            - aws-ecr/build-and-push-image
            - slack/on-hold
          filters:
            branches:
              only:
                - master

      - aws-eks/update-container-image:
          name: deploy-to-prod
          requires:
            - hold
          context:
            - hexa-master
          cluster-name: $EKS_CLUSTER_NAME
          aws-region: $AWS_REGION
          resource-name: "deployment/workmgt"
          container-image-updates: "beee-workmgt=$AWS_ECR_ACCOUNT_URL/beee-workmgt:$CIRCLE_SHA1"
          get-rollout-status: true
          watch-rollout-status: true
          namespace: default
          record: true
          
      - notify-on-success:
          name: notify-on-success-prod
          requires:
            - deploy-to-prod
          context: 
            - slack-secrets