kind: Deployment
apiVersion: apps/v1
metadata:
  name: workmgt
  labels:
    app: workmgt
    component: microservice
spec:
  selector:
    matchLabels:
      app: workmgt
      component: microservice
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  template:
    metadata:
      name: workmgt
      labels:
        app: workmgt
        component: microservice
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: beee-workmgt
        image: 348686912638.dkr.ecr.ap-northeast-1.amazonaws.com/beee-workmgt
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        env:
          - name: NODE_ENV
            value: dev
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits: {}
        imagePullPolicy: Always
        ports:
        - name: workmgt
          containerPort: 80
      nodeSelector:
        eks.amazonaws.com/nodegroup: nodepoolhx